version: '2'

services:


  #######################################
  # phpMyAdmin
  #######################################
  phpmyadmin:
    build: ./phpmyadmin/
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "80:80"
#    volumes:
#      - /sessions


  #######################################
  # MySQL server
  # See https://hub.docker.com/r/hypriot/rpi-mysql/
  #######################################
  mysql:
    build: ./mysql/
#    volumes_from:
#      - storage
#    volumes:
#      - /code/:/app/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword

#  #######################################
#  # Storage
#  #######################################
#  storage:
#    build: ./storage/
#    volumes:
#      - /var/tmp/docker-storage/:/storage

  #######################################
  # UI for containers
  # See https://blog.hypriot.com/post/new-docker-ui-portainer/
  #######################################
  ui:
    image: hypriot/rpi-dockerui
#    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    expose:
      - 9000
    ports:
      - 81:9000
