version: '2'

services:

  #######################################
  # Web Server
  #######################################
  webserver:
    image: hypriot/rpi-busybox-httpd
    ports:
      - 80:80


  #######################################
  # phpMyAdmin
  #######################################
  phpmyadmin:
    build: ./phpmyadmin/
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 81:80


  #######################################
  # MySQL server
  # See https://hub.docker.com/r/hypriot/rpi-mysql/
  #######################################
  mysql:
    build: ./mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - 3306:3306

  #######################################
  # UI for containers
  # See https://blog.hypriot.com/post/new-docker-ui-portainer/
  #######################################
  ui:
    image: hypriot/rpi-dockerui
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - 82:9000
